dbt_demo:
  outputs:
    dev:
      account: blqsppw-ha53517
      database: dbt_test
      password: ***
      role: ACCOUNTADMIN
      schema: seeds
      threads: 10
      type: snowflake
      user: ***
      warehouse: COMPUTE_WH
      client_session_keep_alive: False
      query_tag: warehouse
  target: dev
elementary:
  target: elementary
  outputs:
    elementary:
      account: blqsppw-ha53517
      database: pipeline_logs
      password: ***
      role: ACCOUNTADMIN
      schema: dbt_elementary
      threads: 10
      type: snowflake
      user: ***
      warehouse: COMPUTE_WH
